# Site settings
title: pickadate.js
description: > #
  The mobile-friendly, responsive, and lightweight jQuery date & time input picker.

url: http://amsul.ca
baseurl: /pickadate.js


# Pickadate settings
project:
  version: 3.6.1
  license: MIT
  repo: http://github.com/amsul/pickadate.js
  bugs: http://github.com/amsul/pickadate.js/issues


# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
